In [1]:
import pandas as pd

In [2]:
dados = {
    'TIMES': ['Flamengo', 'Palmeiras', 'São Paulo', 'Santos', 'Corinthians'],
    'PARTIDAS JOGADAS': [10,10,10,10,10],
    'VITÓRIAS': [7,6,5,4,3],
    'EMPATES': [2,3,1,3,2],
    'Derrotas': [1,2,3,3,5],
    'GOLS_PRO': [22,18,16,14,10],
    'GOLS_CONTRA': [10,12,15,16,20],
    
}

In [3]:
df = pd.DataFrame(dados)
df

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA
0,Flamengo,10,7,2,1,22,10
1,Palmeiras,10,6,3,2,18,12
2,São Paulo,10,5,1,3,16,15
3,Santos,10,4,3,3,14,16
4,Corinthians,10,3,2,5,10,20

In [12]:
df['SALDO_GOLS'] = df['GOLS_PRO'] - df['GOLS_CONTRA']
df

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,6,3,2,18,12,6,21
2,São Paulo,10,5,1,3,16,15,1,16
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [10]:
df = df.drop('PONTOS', axis=1)

In [11]:
df['PONTOS'] = df['VITÓRIAS'] *3 + df['EMPATES'] * 1

In [13]:
df = df.sort_values(by='PONTOS', ascending=False)
df

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,6,3,2,18,12,6,21
2,São Paulo,10,5,1,3,16,15,1,16
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [15]:
df.to_excel("dados/campeonato_futebas.xlsx", index=False)