In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("dados/campeonato_futebas.xlsx")
df

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,6,3,2,18,12,6,21
2,São Paulo,10,5,1,3,16,15,1,16
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [3]:
df.dtypes

TIMES               object
PARTIDAS JOGADAS     int64
VITÓRIAS             int64
EMPATES              int64
Derrotas             int64
GOLS_PRO             int64
GOLS_CONTRA          int64
SALDO_GOLS           int64
PONTOS               int64
dtype: object

In [5]:
df.describe()

,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
count,5.0,5.000000,5.00000,5.00000,5.000000,5.000000,5.000000,5.000000
mean,10.0,5.000000,2.20000,2.80000,16.000000,14.600000,1.400000,17.200000
std,0.0,1.581139,0.83666,1.48324,4.472136,3.847077,8.294577,4.816638
min,10.0,3.000000,1.00000,1.00000,10.000000,10.000000,-10.000000,11.000000
25%,10.0,4.000000,2.00000,2.00000,14.000000,12.000000,-2.000000,15.000000
50%,10.0,5.000000,2.00000,3.00000,16.000000,15.000000,1.000000,16.000000
75%,10.0,6.000000,3.00000,3.00000,18.000000,16.000000,6.000000,21.000000
max,10.0,7.000000,3.00000,5.00000,22.000000,20.000000,12.000000,23.000000

In [6]:
df.head(2)

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
0,Flamengo,10,7,2,1,22,10,12,23
1,Palmeiras,10,6,3,2,18,12,6,21

In [7]:
df.tail(2)

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [10]:
#Análise de desempenho por time
desempenho_info = df[['TIMES','PONTOS', 'VITÓRIAS', 'SALDO_GOLS']].set_index('TIMES')
desempenho_info

             PONTOS  VITÓRIAS  SALDO_GOLS
TIMES
Flamengo         23         7          12
Palmeiras        21         6           6
São Paulo        16         5           1
Santos           15         4          -2
Corinthians      11         3         -10

In [ ]:
#Classificação por maior vitória
time_mais_vitorias = df[df['VITÓRIAS'] == df['VITÓRIAS'].max()]
time_mais_vitorias

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
0,Flamengo,10,7,2,1,22,10,12,23

In [12]:
#Classificação por maior vitória
time_menos_vitorias = df[df['VITÓRIAS'] == df['VITÓRIAS'].min()]
time_menos_vitorias

,TIMES,PARTIDAS JOGADAS,VITÓRIAS,EMPATES,Derrotas,GOLS_PRO,GOLS_CONTRA,SALDO_GOLS,PONTOS
4,Corinthians,10,3,2,5,10,20,-10,11

In [13]:
#Distribuição de gols a favor
df['GOLS_PRO'].value_counts()

GOLS_PRO
22    1
18    1
16    1
14    1
10    1
Name: count, dtype: int64

In [15]:
df['GOLS_PRO'].value_counts()

GOLS_PRO
22    1
18    1
16    1
14    1
10    1
Name: count, dtype: int64

In [16]:
correlacao = df['GOLS_PRO'].corr(df['PONTOS'])
correlacao

np.float64(0.9749005254295221)